[build]
  command = "npm run netlify-build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[context.production.environment]
  VITE_API_URL = "https://clean-u8gn.onrender.com"
